#!/usr/bin/env bash

cat <<EOF
# Copy this file to your gerber directory and name it \`millproject\`
# See \`man pcb2gcode\`

# Set paths to gbr files
back=
drill=
outline=
$(
if [ -n "$DOUBLE_SIDED" ] ; then
    cat <<EOF2
front=

# Alignment pins
# You need to decide where to drill alignment holes.
# For example, you can put them in the middle of the board.
mirror-axis=0mm
EOF2
fi
)

# Machine settings
metric=true
metricoutput=true
zsafe=2
spinup-time=2.5
zchange=0
zchange-absolute=true
g0-vertical-speed=3000
g0-horizontal-speed=3000

# TODO control vacuum - probably better to define custom M codes rather than abusing flood coolant like this
pre-milling-gcode=M8
post-milling-gcode=M9

# Optimization
optimise=0.02mm
#path-finding-limit=?
backtrack=25mm/s


# Milling
mill-diameters=1.0mm,0.39mm
mill-feed=500
# TODO investigate mill-feed-direction (climb vs conventional)
mill-vertfeed=120
mill-speed=20000
zwork=-0.12

# Multi-pass isolation
isolation-width=1.0mm
milling-overlap=50%

# Voronoi mode (not tested)
#voronoi=true
#preserve-thermal-reliefs=true


# Drilling
$(
if [ -n "$DOUBLE_SIDED" ] ; then
    cat <<EOF2
# Even for double sided board, we want to drill from the back side.
# It might be tempting to drill from the front and use the bit to drill
# alignment holes, but that would interfere with back side autolevelling.
EOF2
fi
echo "drill-side=back"
)
zdrill=-1.75
drill-feed=700
drill-speed=20000
drills-available=0.8mm:-0.3mm:+0.1mm,1.0mm:-0.2mm:+0.2mm

zmilldrill=-1.65
milldrill-diameter=1.0
min-milldrill-hole-diameter=1.2  # TODO need 1.0 for 1mm slots
# outline (cut-) feeds and speeds are used

# Outline
cutter-diameter=1.0
zcut=-1.65
cut-feed=200
cut-vertfeed=35
cut-speed=20000
cut-infeed=0.85
cut-side=back
bridges=1mm
zbridges=-0.5mm
bridgesnum=2

# Autolevelling
al-back=1
$(if [ -n "$DOUBLE_SIDED" ] ; then
    echo "al-front=1"
fi
)
software=linuxcnc
al-x=10mm
al-y=10mm
# probing with 3D touch probe should allow us to go faster
al-probefeed=25  # TODO faster ?? - calculate from controller latency
# 100 would probably be fine with 3D probe
al-probecode=G38.2
# TODO this does not autolevel outline and drilling
EOF
