#!/bin/sh
# git config --local filter.candle-settings.clean script/git-filter-candle-settings
sed -e 's/^\(heightmapBorder\(Height\|Width\)\)=[0-9.]*$/\1=1/g;' \
    -e 's/^\(heightmapBorder[XY]\)=[0-9.-]*$/\1=0/g;' \
    -e 's/^\(heightmapGrid[XY]\)=[0-9]*$/\1=2/g;' \
    -e 's/^\(heightmapInterpolationStep[XY]\)=[0-9]*$/\1=2/g;' \
    -e 's/^jogFeed=[0-9]*$/jogFeed=500/g;' \
    -e 's/^lastFolder=.*$/lastFolder=\/home/g;' \
    -e 's/^\(recent\(Commands\|Files\|Heightmaps\)\)=.*$/\1=@Invalid()/g;' \
    -e 's/^\(stored[XYZ]\)=[0-9.-]*$/\1=0/g;' \
    -e 's/^\(\(feed\|rapid\|spindle\)Override\)=true$/\1=false/g;' \
    -e 's/^\(\(feed\|rapid\|spindle\)OverrideValue\)=[0-9]*$/\1=100/g;' \
    -e 's/^\(\(feed\|heightmap\|jog\|spindle\|userCommands\)Panel\)=false/\1=true/g;' \
    -e 's/^spindleSpeed=[0-9]*$/spindleSpeed=1000/g'
